version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     
   
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=~/TestResults/ /p:CoverletOutputFormat=opencover
      - run: 
          shell: powershell.exe
          command: .\.circleci\codecov.ps1 -token 948aac85-7d24-42b3-8fb9-1dd6bf34b0da -fName ~\TestResults\coverage.opencover.xml